-- Zeteo 데이터베이스 스키마
-- 재구성일: 2026-09-02
--
-- 출처와 신뢰도가 항목마다 다르다. 나중에 원본 DB에 접근이 되면 대조할 수 있게 표시해 둔다.
--
--   [원본]  서버 파트가 Supabase에서 내보낸 정의 그대로 — 테이블·컬럼·타입·기본값·단순 FK
--   [복원]  ERD 문서(docs/DB_ERD.html)에 존재와 목적이 기록돼 있던 것을 정의문으로 되살림
--           — UNIQUE 제약, 인덱스 2개, 라벨 복합 FK
--   [추정]  원본을 못 봐서 코드 동작에서 역산한 것 — identity, ON DELETE, CHECK, RLS
--           (원본에 같은 게 있었는지는 모른다. 값 목록 자체는 코드에서 확정한 것이다)
--
-- ⚠️ 원본 DB에서 아직 확인 못 한 것:
--   - 원본의 ON DELETE 동작 — 여기 값은 이 스키마를 쓰는 쪽의 선택이다
--   - 뷰 2개(v_survey_reason_counts, v_survey_free_texts) — 앱 코드가 안 쓰는 걸
--     확인해서(레포 전수) 옮기지 않았다. 필요하면 새로 쓰면 된다.

-- ─────────────────────────────────────────────────────────────
-- 1. enum
-- ─────────────────────────────────────────────────────────────

-- [원본]
CREATE TYPE speaker_type AS ENUM ('human', 'bot', 'system');

-- ─────────────────────────────────────────────────────────────
-- 2. 테이블
-- ─────────────────────────────────────────────────────────────
-- [원본] 컬럼·타입·NOT NULL·DEFAULT
-- [추정] integer PK 5개의 GENERATED ... AS IDENTITY
--        내보낸 정의엔 자동 증가가 빠져 있었다. 앱 코드 어디서도 이 id 들을 직접 넣지
--        않으므로(games 는 fn_start_game 이 RETURNING 으로 받고, 나머지는 마스터 데이터)
--        DB 가 만들어주지 않으면 INSERT 가 바로 실패한다.
--        BY DEFAULT 로 둔 이유: 나중에 원본 데이터를 id 까지 그대로 복원할 때
--        명시적 id 를 넣을 수 있어야 한다(ALWAYS 면 OVERRIDING 절이 필요해진다).

CREATE TABLE categories (
  id integer GENERATED BY DEFAULT AS IDENTITY,
  name text NOT NULL,
  PRIMARY KEY (id)
);

CREATE TABLE words (
  id integer GENERATED BY DEFAULT AS IDENTITY,
  category_id integer NOT NULL,
  text text NOT NULL,
  PRIMARY KEY (id)
);

CREATE TABLE games (
  id integer GENERATED BY DEFAULT AS IDENTITY,
  -- 방 번호. 유니크가 아니다 — 같은 방에서 여러 판을 하면 판마다 행이 쌓인다.
  -- 방 이름·번호 중복은 서버가 방 생성 단계에서 막는다(index.ts 의 'join' 처리):
  -- 이미 있는 방이면 그 방에 입장시키고, 없는 번호로 title 없이 들어오면 "없는 방입니다"로
  -- 거절한다. 즉 DB 가 관여할 문제가 아니다.
  room_id text NOT NULL,
  category text NOT NULL,
  word text NOT NULL,
  -- category/word 는 FK 가 아니라 글자 그대로 저장한다.
  -- "기록은 사진이지 링크가 아니다" — 나중에 단어 목록을 갈아도 지난 판의 기록은 안 변한다.
  bot_label text NOT NULL,
  liar_label text NOT NULL,
  liar_game_result text,
  bot_detected_count integer NOT NULL DEFAULT 0,
  bot_voter_total integer NOT NULL DEFAULT 0,
  final_round integer NOT NULL DEFAULT 1,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  ended_at timestamp with time zone,
  -- 판마다 "실제로 어떤 봇이 돌았는지". SHA 만으로는 부족하다 —
  -- /x/provider 가 재배포 없이 프로바이더를 바꿔서 같은 SHA 에 다른 봇인 판이 생긴다.
  bot_commit_sha text,
  bot_provider text,
  bot_model text,
  PRIMARY KEY (id)
);

CREATE TABLE players (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  game_id integer NOT NULL,
  player_label text NOT NULL,
  is_bot boolean NOT NULL DEFAULT false,
  role text NOT NULL,
  PRIMARY KEY (id)
);

CREATE TABLE game_messages (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  game_id integer NOT NULL,
  speaker_label text,          -- 시스템 메시지는 화자가 없다
  speaker_type speaker_type NOT NULL,
  role text,                   -- 시스템 메시지는 역할도 없다
  round integer NOT NULL DEFAULT 1,
  phase text NOT NULL,
  text text NOT NULL,
  at timestamp with time zone NOT NULL DEFAULT now(),
  -- 화면이 들고 있는 Message.id(m{ts}_{rand} / sys{ts}_{n}).
  -- PK(uuid)는 DB 가 만든 값이라 "화면에서 고른 그 발언"을 되짚을 수 없어서 칸을 더했다.
  runtime_id text,
  PRIMARY KEY (id)
);

CREATE TABLE game_votes (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  game_id integer NOT NULL,
  round integer NOT NULL DEFAULT 1,
  vote_type text NOT NULL,
  phase text NOT NULL,
  voter_label text NOT NULL,
  -- 기권은 아예 기록하지 않는다(index.ts 가 targetId 가 있을 때만 logVote 를 부른다).
  -- 그래서 이 칸은 항상 실재하는 참가자 라벨이고, 아래 복합 FK 를 걸 수 있다.
  target_label text NOT NULL,
  at timestamp with time zone NOT NULL DEFAULT now(),
  PRIMARY KEY (id)
);

CREATE TABLE survey_questions (
  id integer GENERATED BY DEFAULT AS IDENTITY,
  code text NOT NULL,
  text text NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  description text,
  -- 문항은 덮어쓰지 않고 세대별로 쌓는다. 코드는 활성 세대 하나만 읽는다.
  is_active boolean NOT NULL DEFAULT false,
  PRIMARY KEY (id)
);

CREATE TABLE survey_reasons (
  id integer GENERATED BY DEFAULT AS IDENTITY,
  question_id integer NOT NULL,
  code text NOT NULL,
  text text NOT NULL,
  sort_order integer NOT NULL DEFAULT 0,
  is_other boolean NOT NULL DEFAULT false,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  PRIMARY KEY (id)
);

CREATE TABLE survey_responses (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  game_id integer NOT NULL,
  voter_label text NOT NULL,
  -- 봇 지목(20초 타이머)을 놓치면 이 두 칸이 null 이다. 지목과 설문은 별개 정보라
  -- 하나가 없다고 설문 본문까지 버리지 않는다.
  -- "지목 안 함" = guessed_bot_label IS NULL / "지목했는데 틀림" = guessed_correctly = false
  guessed_bot_label text,
  guessed_correctly boolean,
  free_text text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  -- "가장 봇 같았던 발언"으로 고른 game_messages.runtime_id. 안 골랐으면 null.
  picked_message_runtime_id text,
  PRIMARY KEY (id)
);

CREATE TABLE survey_response_reasons (
  survey_response_id uuid NOT NULL,
  reason_id integer NOT NULL,
  free_text text,
  PRIMARY KEY (survey_response_id, reason_id)
);

-- ─────────────────────────────────────────────────────────────
-- 3. UNIQUE 제약 · 인덱스
-- ─────────────────────────────────────────────────────────────
-- [복원] ERD 가 UK 로 표시했거나 이름과 목적을 적어둔 것들.

ALTER TABLE survey_questions ADD CONSTRAINT uniq_survey_questions_code UNIQUE (code);

-- 라벨 복합 FK 의 참조 대상. 같은 판 안에서 라벨은 유일하다.
ALTER TABLE players ADD CONSTRAINT uniq_players_game_label UNIQUE (game_id, player_label);

-- 발언 조인을 1:1 로 보장. runtime_id 가 null 인 옛 행이 여럿 있어도
-- Postgres 는 null 을 서로 다른 값으로 보므로 충돌하지 않는다.
CREATE UNIQUE INDEX uniq_game_messages_runtime ON game_messages (game_id, runtime_id);

-- 활성 문항은 항상 최대 1개. 둘이 켜지면 fetchSurveyReasons 의 .single() 이 에러로
-- 떨어져 설문 선택지가 통째로 안 뜬다 — 그걸 DB 에서 막는다.
-- 문항 세대를 올릴 때는 먼저 기존 행을 is_active=false 로 내려야 한다.
CREATE UNIQUE INDEX uniq_survey_questions_active ON survey_questions (is_active) WHERE is_active;

-- ─────────────────────────────────────────────────────────────
-- 4. 외래키
-- ─────────────────────────────────────────────────────────────
-- [원본] 단순 FK / [복원] 라벨 복합 FK / [추정] ON DELETE 동작

ALTER TABLE words
  ADD CONSTRAINT fk_words_category
  FOREIGN KEY (category_id) REFERENCES categories(id) ON DELETE RESTRICT;

ALTER TABLE survey_reasons
  ADD CONSTRAINT fk_survey_reasons_question
  FOREIGN KEY (question_id) REFERENCES survey_questions(id) ON DELETE RESTRICT;

-- games 를 지우면 그 판의 기록도 같이 지운다. 판 없이 남은 발언·투표는 의미가 없다.
ALTER TABLE players
  ADD CONSTRAINT fk_players_game
  FOREIGN KEY (game_id) REFERENCES games(id) ON DELETE CASCADE;

ALTER TABLE game_messages
  ADD CONSTRAINT fk_game_messages_game
  FOREIGN KEY (game_id) REFERENCES games(id) ON DELETE CASCADE;

ALTER TABLE game_votes
  ADD CONSTRAINT fk_game_votes_game
  FOREIGN KEY (game_id) REFERENCES games(id) ON DELETE CASCADE;

ALTER TABLE survey_responses
  ADD CONSTRAINT fk_survey_responses_game
  FOREIGN KEY (game_id) REFERENCES games(id) ON DELETE CASCADE;

ALTER TABLE survey_response_reasons
  ADD CONSTRAINT fk_srr_response
  FOREIGN KEY (survey_response_id) REFERENCES survey_responses(id) ON DELETE CASCADE;

-- 선택지를 지우면 그걸 고른 응답이 뜻을 잃는다. 지우지 못하게 막고, 문항을 갈 때는
-- 삭제 대신 새 세대를 INSERT 한다(is_active 전환).
ALTER TABLE survey_response_reasons
  ADD CONSTRAINT fk_srr_reason
  FOREIGN KEY (reason_id) REFERENCES survey_reasons(id) ON DELETE RESTRICT;

-- 라벨 매칭 복합 FK — "이 라벨이 같은 판에 실제로 있는 참가자인가"를 DB 가 보장한다.
--
-- ★ games 쪽만 DEFERRABLE INITIALLY DEFERRED 다. fn_start_game 이 games 행을 먼저
--   넣고 그 id 로 players 를 넣기 때문에, 즉시 검사면 games INSERT 가 그 자리에서
--   실패한다. 트랜잭션 끝에 검사하도록 미뤄야 게임 시작이 성립한다.
--   (원본도 이 형태여야만 동작한다 — 원본 정의를 확인하면 여기부터 대조할 것.)
ALTER TABLE games
  ADD CONSTRAINT fk_games_bot_label
  FOREIGN KEY (id, bot_label) REFERENCES players(game_id, player_label)
  DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE games
  ADD CONSTRAINT fk_games_liar_label
  FOREIGN KEY (id, liar_label) REFERENCES players(game_id, player_label)
  DEFERRABLE INITIALLY DEFERRED;

-- 아래 셋은 players 가 이미 있는 시점에만 쓰이므로 즉시 검사여도 된다.
ALTER TABLE game_messages
  ADD CONSTRAINT fk_game_messages_speaker
  FOREIGN KEY (game_id, speaker_label) REFERENCES players(game_id, player_label);

ALTER TABLE game_votes
  ADD CONSTRAINT fk_game_votes_voter
  FOREIGN KEY (game_id, voter_label) REFERENCES players(game_id, player_label);

ALTER TABLE game_votes
  ADD CONSTRAINT fk_game_votes_target
  FOREIGN KEY (game_id, target_label) REFERENCES players(game_id, player_label);

ALTER TABLE survey_responses
  ADD CONSTRAINT fk_survey_responses_voter
  FOREIGN KEY (game_id, voter_label) REFERENCES players(game_id, player_label);

-- ─────────────────────────────────────────────────────────────
-- 5. CHECK 제약
-- ─────────────────────────────────────────────────────────────
-- [추정] 원본에 있었는지 모른다. 값 목록은 코드에서 그대로 가져왔다:
--   Phase  = packages/shared-types/src/index.ts
--   Role   = 같은 파일 ('citizen' | 'liar')
--   투표종류 = apps/backend/src/db/log.ts 의 logVote 시그니처
-- 페이즈를 새로 추가할 계획이면 이 절을 통째로 지워도 된다 — 안전망이지 필수가 아니다.

ALTER TABLE players
  ADD CONSTRAINT chk_players_role CHECK (role IN ('citizen', 'liar'));

ALTER TABLE game_messages
  ADD CONSTRAINT chk_game_messages_role CHECK (role IS NULL OR role IN ('citizen', 'liar'));

ALTER TABLE game_votes
  ADD CONSTRAINT chk_game_votes_type CHECK (vote_type IN ('liar_vote', 'life_vote'));

ALTER TABLE game_messages
  ADD CONSTRAINT chk_game_messages_phase CHECK (phase IN (
    'lobby', 'roleReveal', 'describe', 'debate', 'finalDefense',
    'lifeVote', 'reveal', 'guessWord', 'botVote', 'result', 'survey'
  ));

ALTER TABLE game_votes
  ADD CONSTRAINT chk_game_votes_phase CHECK (phase IN (
    'lobby', 'roleReveal', 'describe', 'debate', 'finalDefense',
    'lifeVote', 'reveal', 'guessWord', 'botVote', 'result', 'survey'
  ));

-- [복원] games.liar_game_result — 값 목록을 코드에서 확정했다(2026-09-02).
--   packages/shared-types/src/index.ts: liarGameResult: 'liarWin' | 'citizenWin' | null
--   apps/backend/src/db/game.ts:73 이 그 값을 그대로 넣는다(변환 없음).
-- null 은 "아직 안 끝난 판" — finalizeGame 전이거나 라이어 게임이 결판나기 전 상태다.
ALTER TABLE games
  ADD CONSTRAINT chk_games_liar_result
  CHECK (liar_game_result IS NULL OR liar_game_result IN ('liarWin', 'citizenWin'));

-- ─────────────────────────────────────────────────────────────
-- 6. 함수
-- ─────────────────────────────────────────────────────────────
-- [원본] ✅ 2026-09-02 에 실제 정의를 받아 그대로 넣었다(pg_get_functiondef 결과).
--        저장소엔 정의가 없고 DB 안에만 있던 함수다
--        (apps/backend/src/db/game.ts 주석: "그 정의가 저장소에 없다(DB 안에만 있음)").
--
-- 원본을 받아보고 확인된 것:
--   · games 행을 먼저 넣고 그 id 로 players 를 넣는다 → 위 games 쪽 라벨 복합 FK 는
--     반드시 DEFERRABLE INITIALLY DEFERRED 여야 한다. 즉시 검사면 첫 INSERT 에서
--     "참가자가 아직 없다"로 실패한다.
--   · 방 번호 중복은 이 함수가 신경 쓰지 않는다 — 방 생성 단계에서 서버가 이미 거른다
--     (games.room_id 주석 참고).
--   · RETURNS bigint 인데 games.id 는 integer 다. 1차 설계에서 PK 가 bigint 였던 흔적으로
--     보인다(나중에 integer 로 바꾸면서 함수 시그니처는 안 건드림). integer → bigint 는
--     암묵적으로 넓어지므로 동작에 문제가 없어 원본 그대로 둔다.
--
-- 참고: Supabase 린터는 search_path 가 고정되지 않은 함수에 경고를 낸다. 이 함수는
--       SECURITY INVOKER(기본값)라 위험이 낮아 원본을 그대로 뒀다. 경고를 없애려면
--       LANGUAGE plpgsql 줄 다음에 `SET search_path = public` 한 줄을 넣으면 된다.

CREATE OR REPLACE FUNCTION public.fn_start_game(p_room_id text, p_category text, p_word text, p_bot_label text, p_liar_label text, p_players jsonb)
 RETURNS bigint
 LANGUAGE plpgsql
AS $function$
declare
  v_game_id bigint;
begin
  insert into games (room_id, category, word, bot_label, liar_label)
  values (p_room_id, p_category, p_word, p_bot_label, p_liar_label)
  returning id into v_game_id;

  insert into players (game_id, player_label, is_bot, role)
  select v_game_id, (p)->>'label', ((p)->>'is_bot')::bool, (p)->>'role'
  from jsonb_array_elements(p_players) as p;

  return v_game_id;
end;
$function$;

-- ─────────────────────────────────────────────────────────────
-- 7. RLS
-- ─────────────────────────────────────────────────────────────
-- [추정] 원본 정책을 못 봤다.
-- 백엔드는 service_role 키로만 붙고(apps/backend/src/db/supabase.ts), 프론트엔드는
-- Supabase 를 아예 안 쓴다(레포 전수 확인 — import.meta.env 사용처 0건).
-- service_role 은 RLS 를 통과하므로, 정책 없이 켜두면 "서버만 접근 가능"이 된다.
-- anon 키가 유출돼도 테이블이 통째로 열리지 않는다.

ALTER TABLE categories             ENABLE ROW LEVEL SECURITY;
ALTER TABLE words                  ENABLE ROW LEVEL SECURITY;
ALTER TABLE games                  ENABLE ROW LEVEL SECURITY;
ALTER TABLE players                ENABLE ROW LEVEL SECURITY;
ALTER TABLE game_messages          ENABLE ROW LEVEL SECURITY;
ALTER TABLE game_votes             ENABLE ROW LEVEL SECURITY;
ALTER TABLE survey_questions       ENABLE ROW LEVEL SECURITY;
ALTER TABLE survey_reasons         ENABLE ROW LEVEL SECURITY;
ALTER TABLE survey_responses       ENABLE ROW LEVEL SECURITY;
ALTER TABLE survey_response_reasons ENABLE ROW LEVEL SECURITY;

-- ─────────────────────────────────────────────────────────────
-- 8. 마스터 데이터
-- ─────────────────────────────────────────────────────────────
-- [원본] ✅ 2026-09-02 에 팀 DB 의 실제 주제·단어를 받아 그대로 넣었다 (12주제 × 8단어 = 96).
-- id 를 직접 안 쓰고 이름으로 조인해서 넣는다 — identity 시퀀스가 어긋나지 않는다.

INSERT INTO categories (name) VALUES
  ('동물'), ('음식'), ('과일'), ('채소'), ('직업'), ('스포츠'),
  ('탈것'), ('가전제품'), ('여행지'), ('학용품'), ('악기'), ('취미');

INSERT INTO words (category_id, text)
SELECT c.id, w.word
FROM categories c
JOIN (VALUES
  ('동물', '사자'), ('동물', '코끼리'), ('동물', '기린'), ('동물', '판다'),
  ('동물', '캥거루'), ('동물', '펭귄'), ('동물', '호랑이'), ('동물', '낙타'),

  ('음식', '김치찌개'), ('음식', '짜장면'), ('음식', '피자'), ('음식', '초밥'),
  ('음식', '떡볶이'), ('음식', '삼겹살'), ('음식', '라면'), ('음식', '파스타'),

  ('과일', '사과'), ('과일', '바나나'), ('과일', '딸기'), ('과일', '수박'),
  ('과일', '포도'), ('과일', '복숭아'), ('과일', '파인애플'), ('과일', '참외'),

  ('채소', '당근'), ('채소', '양파'), ('채소', '감자'), ('채소', '오이'),
  ('채소', '브로콜리'), ('채소', '고구마'), ('채소', '마늘'), ('채소', '파'),

  ('직업', '의사'), ('직업', '변호사'), ('직업', '소방관'), ('직업', '경찰관'),
  ('직업', '요리사'), ('직업', '선생님'), ('직업', '미용사'), ('직업', '개발자'),

  ('스포츠', '축구'), ('스포츠', '야구'), ('스포츠', '농구'), ('스포츠', '배구'),
  ('스포츠', '수영'), ('스포츠', '골프'), ('스포츠', '테니스'), ('스포츠', '볼링'),

  ('탈것', '자동차'), ('탈것', '비행기'), ('탈것', '기차'), ('탈것', '자전거'),
  ('탈것', '오토바이'), ('탈것', '버스'), ('탈것', '배'), ('탈것', '헬리콥터'),

  ('가전제품', '냉장고'), ('가전제품', '세탁기'), ('가전제품', '에어컨'), ('가전제품', '전자레인지'),
  ('가전제품', '청소기'), ('가전제품', '텔레비전'), ('가전제품', '정수기'), ('가전제품', '선풍기'),

  ('여행지', '제주도'), ('여행지', '파리'), ('여행지', '도쿄'), ('여행지', '뉴욕'),
  ('여행지', '하와이'), ('여행지', '방콕'), ('여행지', '런던'), ('여행지', '부산'),

  ('학용품', '연필'), ('학용품', '지우개'), ('학용품', '볼펜'), ('학용품', '필통'),
  ('학용품', '노트'), ('학용품', '가위'), ('학용품', '풀'), ('학용품', '자'),

  ('악기', '피아노'), ('악기', '기타'), ('악기', '드럼'), ('악기', '바이올린'),
  ('악기', '트럼펫'), ('악기', '플루트'), ('악기', '첼로'), ('악기', '하모니카'),

  ('취미', '독서'), ('취미', '등산'), ('취미', '낚시'), ('취미', '게임'),
  ('취미', '요리'), ('취미', '그림그리기'), ('취미', '사진찍기'), ('취미', '캠핑')
) AS w(category_name, word) ON w.category_name = c.name;

-- [신규] 설문 문항은 원본을 받지 못해 새로 만든 1세대다(선택지 5개는 사용자 지정).
-- 원본 문구를 나중에 구하면, 덮어쓰지 말고 새 세대를 INSERT 하는 게 이 스키마의 규칙이다
-- (기존 행 is_active=false 로 내린 뒤 새 행을 true 로 — README 의 "DB (Supabase)" 절).
-- 활성 문항은 항상 하나여야 한다(uniq_survey_questions_active).
INSERT INTO survey_questions (code, text, is_active) VALUES
  ('bot_reason_v1', '왜 봇이라고 생각했나요?', true);

INSERT INTO survey_reasons (question_id, code, text, sort_order, is_other)
SELECT q.id, v.code, v.text, v.sort_order, v.is_other
FROM survey_questions q
JOIN (VALUES
  ('wrong_content',    '발언 내용이 틀렸다',              1, false),
  ('off_context',      '발언 내용이 맥락에 맞지 않았다',    2, false),
  ('leaked_word',      '제시어를 흘렸다',                3, false),
  ('odd_timing',       '발언 타이밍이 이상했다',          4, false),
  ('knew_hidden_info', '공개되지 않은 정보를 알고 있다',    5, false)
) AS v(code, text, sort_order, is_other) ON q.code = 'bot_reason_v1';

-- "기타(자유 서술)" 선택지는 넣지 않았다. 필요하면 아래 한 줄을 더 실행하면 된다.
-- 현재 fetchSurveyReasons 는 is_other 를 읽기만 하고 화면에 다르게 쓰지는 않는다 —
-- 자유 서술은 survey_responses.free_text 로 따로 받는다.
--
-- INSERT INTO survey_reasons (question_id, code, text, sort_order, is_other)
-- SELECT id, 'other', '기타', 6, true FROM survey_questions WHERE code = 'bot_reason_v1';
